version: '3.8'
services:
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=alexander
      - POSTGRES_PASSWORD=1qazXsw2
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres:
